config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :favorites, only: [:index]
  resources :favorites, only: [:create, :destroy]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root 'tops#index'
  resources :comments
  resources :blogs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, PictureUploader
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
belongs_to :blog, optional:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
           has_many :blogs
           has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show

    @comments = @blog.comments.all

    @comment = @blog.comments.build

    @favorite = current_user.favorites.find_by(blog_id: @blog.id)

  end


  # GET /blogs/new
  def new
    @blog = current_user.blogs.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
     @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :suggest, :blog_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController



  def index

      @favorites = current_user.favorites

    end

    def create

      favorite = current_user.favorites.create(blog_id: params[:blog_id])

      redirect_to blogs_path, notice: "#{favorite.blog.user.email}'s post has been added to favorites"

    end

    def destroy

      favorite = current_user.favorites.find_by(id: params[:id]).destroy

      redirect_to blogs_path, notice: "#{favorite.blog.user.email}'s post has been removed to favorites"

    end

    def index

      @favorites = current_user.favorites

    end

  end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Blogs</h1>



<table class="table">

  <thead>

    <tr>

      <th>Blog Author</th>

      <th>Title</th>

      <th>Content</th>

      <th>Image</th>

      <th colspan="3"></th>

    </tr>

  </thead>



  <tbody>

    <% @blogs.each do |blog| %>

      <tr>

        <td><%= blog.user.email %></td>

        <td><%= blog.title %></td>

        <td><%= blog.content %></td>

        <td><%= image_tag(blog.image_url,class:'show_image') if blog.image.present? %></td>

        <td><%= link_to 'Show', blog %></td>

        <% if current_user.id == blog.user_id %>

          <td><%= link_to 'Edit', edit_blog_path(blog) %></td>

          <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% end %>

      </tr>

    <% end %>

  </tbody>

</table>



<br>



<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>

  <strong>Title:</strong>

  <%= @blog.title %>

</p>



<p>

  <strong>Content:</strong>

  <%= @blog.content %>

</p>



<p>

  <strong>Image:</strong>

<%= image_tag @blog.image_url, class:'show_image' if @blog.image.present?  %>

</p>



<%= link_to 'Edit', edit_blog_path(@blog) %> |

<%= link_to 'Back', blogs_path %>



<% unless @blog.user_id == current_user.id %>

  <% if @favorite.present? %>

    <%= link_to 'Unfavorite', favorite_path(id: @favorite.id), method: :delete, class:'btn btn-danger' %>

  <% else %>

    <%= link_to 'Favorite', favorites_path(blog_id: @blog.id), method: :blog, class:'btn btn-primary'%>

  <% end %>

  <% end %>

<hr>

<h3>Comments</h3>

<% @comments.each do |comment| %>

  <div>

    <strong><%= comment.user_id %></strong>

    <br>

    <p><%= comment.suggest %></p>

    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>

  </div>

  <% end %>



<%= render partial: 'comments/form', locals: { comment: @comment } %><br>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :suggest %>
    <%= form.text_area :suggest %>
  </div>
<%= form.hidden_field :blog_id %>

    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Suggest</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.suggest %></td>
        <td><%= comment.blog_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Suggest:</strong>
  <%= @comment.suggest %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @comment.blog_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunrise Sports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul>

        <li><a href="#">Sunrise Sports</a></li>

        <li><a href="#">Daily Football News</a></li>

        <% if current_user %>

          <li><%= link_to "Blogs", blogs_path, class:"navbar-item" %></li>

          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %></li>

        <% else %>

          <li><%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%><l/i>

          <li><%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %></li>

        <% end %>

      </ul>
        </header>
    <%= yield %>
    <footer>
      <p>Your No.1 Football  news blog!!</p>
          </footer>
  </body>
</html>

app/views/tops/index.html.erb
<div class="container">
  <h1 class="title">Bootstrap</h1>
    <nav class="menu">
      <ul>
        <li>top</li>
        <li>menu1</li>
        <li>menu2</li>
      </ul>
    </nav>
  <article>
    <div class="contents">
      <ul>
        <li>contents1</li>
        <li>contents2</li>
      </ul>
    </div>
    <div class="topic">
      <ul>
        <li>Realize responsive design with bootstrap!</li>
        <li>you can do it if you try! Let's use bootstrap!</li>
        <li>Not scary! If responsive design becomes possible, Web applications will be upgraded.</li>
      </ul>
    </div>
  </article>
</div>